name: Acceptance Tests

on:
  push:
  pull_request:

jobs:
  test-acceptance:
    strategy:
      fail-fast: false
      matrix:
        php_version:
          - "8.0"  # Test with PHP 8.0
          # Uncomment the line below to also test with PHP 8.4
          # - "8.4"
        operating_system:
          - image: docker.io/jrei/systemd-ubuntu:20.04  # Base image with PHP 8.0
    runs-on: ubuntu-latest

    steps:
      - name: Replace Docker with Podman
        run: sudo apt-get -o Dpkg::Options::="--force-overwrite" install -y podman-docker

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - uses: actions/checkout@v3

      - name: Compile SaltStack bootstrap wrapper
        run: CGO_ENABLED=0 go build -ldflags "-s -w" -o ./salt-bootstrap salt-bootstrap.go
        working-directory: ./e107_tests/lib/ci/salt/

      - name: Launch test container
        run: docker run -d -it --rm --name target -v .:/app/ ${{ matrix.operating_system.image }}

      - name: Install SaltStack
        run: docker exec target /app/e107_tests/lib/ci/salt/salt-bootstrap onedir

      - name: Apply Salt state
        run: |
          ln -v -s master minion
          rm -fv pillars/config.sls
          touch pillars/config.sls
          rm -fv pillars/config-sample.sls
          touch pillars/config-sample.sls
          ln -v -s -f ../../config.acceptance.ci.yml pillars/config-local.sls
          docker exec -w /app/e107_tests/lib/ci/salt/ target /bin/sh -c "
            salt-call -c ./ --id=e107-dev --local state.apply e107-dev ||
            salt-call -c ./ --id=e107-dev --local state.apply e107-dev
          "
        working-directory: ./e107_tests/lib/ci/salt/

      - name: Install PHP and extensions
        run: |
          docker exec target apt-get update
          docker exec target apt-get install -y software-properties-common
          # Add ondrej/php PPA for PHP 8.4 support (optional)
          docker exec target add-apt-repository ppa:ondrej/php -y
          docker exec target apt-get update
          # Install PHP and required extensions
          docker exec target apt-get install -y php${{ matrix.php_version }} php${{ matrix.php_version }}-zip php${{ matrix.php_version }}-curl php${{ matrix.php_version }}-mbstring php${{ matrix.php_version }}-xml
          # Set the specified PHP version as the default
          docker exec target update-alternatives --set php /usr/bin/php${{ matrix.php_version }}
        # Note: For PHP 8.0 on Ubuntu 20.04, this step will essentially ensure the default version is used and extensions are installed.

      - name: Verify PHP version
        run: docker exec target php -v
        # This step helps confirm the PHP version in use.

      - name: Install test dependencies
        run: |
          docker exec -w /app/e107_tests/ -e COMPOSER_ALLOW_SUPERUSER=1 target \
          composer update --prefer-dist --no-progress

      - name: Download Git submodule dependencies
        run: git submodule update --init --recursive --remote

      - name: Install the CI test configuration file
        run: |
          ln -v -s -f ./lib/ci/config.acceptance.ci.yml ./e107_tests/config.yml

      - name: Run acceptance tests
        run: docker exec -w /app/e107_tests/ target php ./vendor/bin/codecept run acceptance --steps