name: Acceptance Tests

on:
  push:
  pull_request:

jobs:
  test-acceptance:
    strategy:
      fail-fast: false
      matrix:
        operating_system:
          - image: docker.io/jrei/systemd-ubuntu:22.04  # Uses PHP 8.1 by default
    runs-on: ubuntu-latest

    steps:
      - name: Replace Docker with Podman
        run: sudo apt-get -o Dpkg::Options::="--force-overwrite" install -y podman-docker

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - uses: actions/checkout@v3

      - name: Compile SaltStack bootstrap wrapper
        run: CGO_ENABLED=0 go build -ldflags "-s -w" -o ./salt-bootstrap salt-bootstrap.go
        working-directory: ./e107_tests/lib/ci/salt/

      - name: Launch test container
        run: docker run -d -it --rm --name target -v .:/app/ ${{ matrix.operating_system.image }}

      - name: Install SaltStack
        run: docker exec target /app/e107_tests/lib/ci/salt/salt-bootstrap onedir

      - name: Apply Salt state
        run: |
          ln -v -s master minion
          rm -fv pillars/config.sls
          touch pillars/config.sls
          rm -fv pillars/config-sample.sls
          touch pillars/config-sample.sls
          ln -v -s -f ../../config.acceptance.ci.yml pillars/config-local.sls
          docker exec -w /app/e107_tests/lib/ci/salt/ target /bin/sh -c "
            salt-call -c ./ --id=e107-dev --local state.apply e107-dev ||
            salt-call -c ./ --id=e107-dev --local state.apply e107-dev
          "
        working-directory: ./e107_tests/lib/ci/salt/

      - name: Install PHP extensions
        run: |
          docker exec target apt-get update
          docker exec target apt-get install -y php8.1-zip php8.1-curl php8.1-mbstring php8.1-xml
        # Install extensions for PHP 8.1 (default in Ubuntu 22.04)

      - name: Verify PHP version
        run: docker exec target php -v
        # Confirms PHP 8.1 is in use

      - name: Install test dependencies
        run: |
          docker exec -w /app/e107_tests/ -e COMPOSER_ALLOW_SUPERUSER=1 target \
          composer update --prefer-dist --no-progress

      - name: Download Git submodule dependencies
        run: git submodule update --init --recursive --remote

      - name: Install the CI test configuration file
        run: |
          ln -v -s -f ./lib/ci/config.acceptance.ci.yml ./e107_tests/config.yml

      - name: Run acceptance tests
        run: docker exec -w /app/e107_tests/ target php ./vendor/bin/codecept run acceptance --steps